# Generated by Django 3.2.13 on 2022-06-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210923_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[], default='Europe/Moscow', max_length=32, verbose_name='Временная зона'),
        ),
    ]
