#-*- coding: utf-8 -*-
"""
Django settings for trambroid project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.utils.translation import ugettext_lazy as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SITE_ID = 1

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.trambroid.com']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # TRAMBROID apps
    'apps.core',
    'apps.tag',
    'apps.user_profile',
    'apps.content',
    'apps.drupal',

    # External apps
    'voting',
    'taggit',
    'parler',
    'social.apps.django_app.default',
    'mptt',
    'imagekit',
    'registration',
    'linkexchange_django',
    'static_precompiler',
    'social_django',
)

MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'apps.core.middleware.LanguageMiddleware',
)

ROOT_URLCONF = 'trambroid.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.content.context_processors.last_comments',
                'linkexchange_django.context_processors.linkexchange'
            ],
        },
    },
]

WSGI_APPLICATION = 'trambroid.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, '..', 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGES = (
    ('ru', u'Русский'),
    ('en', u'English')
)

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

AUTHENTICATION_BACKENDS = (
    'apps.drupal.auth.DrupalAuthenticate',
    'django.contrib.auth.backends.ModelBackend',
    'social.backends.facebook.FacebookOAuth2',
    'social.backends.vk.VKOAuth2',
)

STUPIDITY_LEVELS = (
    (0, '1'),
    (1, '2'),
    (2, '3'),
    (3, '4'),
)

MENU_ITEMS = (
    ('content:list', _(u'Blogs')),
    ('forum:list', _(u'Forums')),
)

DISPLAY_CONTENT_TYPES = (
    'blog',
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'static_precompiler.finders.StaticPrecompilerFinder',
#    'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

AUTH_USER_MODEL = 'user_profile.User'

SOCIAL_AUTH_USER_MODEL = AUTH_USER_MODEL

AUTH_USER_EMAIL_UNIQUE = True

DEFAULT_FROM_EMAIL = 'info@trambroid.com'

ACCOUNT_ACTIVATION_DAYS = 2

REGISTRATION_AUTO_LOGIN = True

REGISTRATION_FORM = 'apps.user_profile.forms.RegistrationForm'

MAX_UPLOAD_SIZE = 10 * 1024 * 1024

QUOTE_REGEX = (
    r'(?P<quote>(?P<tag_open>\[|<)\s*(block)?quote(?:\s*=\s*'
    r'(?P<author>(?:(?!\s*[a-z0-9]+\s*=)[^]^>])+)*)?'
    r'(?P<args>(\s*[a-z0-9]+\s*=\s*"?((?!"?\s*(?:[a-z0-9]+\s*=|[]>])).)+"?\s*)*)'
    r'(?P<tag_close>\]|>)'
    r'(?P<quote_body>(?:(?!(?P=tag_open)\s*\/\s*quote\s*(?P=tag_close)).)*)'
    r'(?P=tag_open)\s*\/\s*quote\s*(?P=tag_close)\s*\n?)'
)

LINKEXCHANGE_CONFIG = os.path.join(BASE_DIR, 'trambroid', 'linkexchange.cfg')

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'apps.user_profile.pipeline.set_user_profile',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
)

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', 'public_profile']

AVATAR_SIZE = (128, 128)

SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['email', 'status']

PARLER_LANGUAGES = {
    1: (
        {'code': 'ru',},
        {'code': 'en',},
    ),
}


try:
    from .local_settings import *
except:
    print('\033[33;2m File "local_settings.py" not found! \033[0m')


PARLER_DEFAULT_LANGUAGE = LANGUAGE_CODE
